export var teluguOutreachContent: any = [
  {
    "id": 2,
    "Title": "Entrepreneurship Awareness Workshop",
    "Date": "14-12-2022",
    "Time": "9:30 AM to 12:30 PM",
    "Venue": "AP Innovation society, Innovation Valley, Visakhapatnam",
    "Eventtype": false,
    "Outcomes": [
      { 0: "Incubators Interaction, main discussion on the various schemes & their fund availability" },
      { 1: "Presentation on APIS Activities & Start-ups Interaction" },
    ],
    "Participants": [
      { 0: "SPMVV Society For Innovation Incubation And Entrepreneurship Technology Business Incubator - Dr. J. Sury Kumar" },
      { 1: "V R Siddhartha TBI Foundation - Dr. Praveeen Naidu" },
      { 2: "Gayatri Vidya Parishad - Dr. Saripalli Ravi" },
      { 3: "VTEC - VITAP Technology Entrepreneurship Centre - Dr. Ellison M.S, Dep., Dir. IIEC" },
      { 4: "KL Technology Incubators Foundation - TBI - Dr. Sunny Agarwal" },
      { 5: "SPMVV-Women Biotech Incubation Facility (SPMVV-WBIF). - Dr. Tulasee Naidu Adari" },
      { 6: "IIIT Sri City (CIEDI), Gyan circle venture (GCV) - Krishnamurthy P, Manager - TBI" },
      { 7: "Grameena Incubation Centre - Mr. Ragavendra" },
      { 8: "A-Hub, (Andhra University Incubation Center) - Dr. Ravi Eswarapu" },
      { 9: "Aditya Global Business Incubator - Srinivas Gogineni" },
      { 10: "Aditya College of Engineering & Technology LBI – Dr. Rama Chandra Murty" },
      { 11: "Andhra Technology Business Incubator - Dr. MVK. Srinivasrao" },
      { 12: "Centre for Entrepreneurship Innovation and Start-ups (EISC) - Dr. MVK. Srinivasa Rao" },
    ],
    "Photographs": [
      { url: 'assets/images/resources/outreach/activities/2/1.png' },
      { url: 'assets/images/resources/outreach/activities/2/2.png' },
      { url: 'assets/images/resources/outreach/activities/2/3.png' },
      { url: 'assets/images/resources/outreach/activities/2/4.png' },
      { url: 'assets/images/resources/outreach/activities/2/5.png' },
    ],
  },
  {
    "id": 1,
    "Title": "Manage Agri - Startup Workshop",
    "Date": "13-10-2022",
    "Time": "12:00 PM to 2:00 PM",
    "Venue": "AP Innovation society, Innovation Valley, Visakhapatnam",
    "Eventtype": "",
    "meetdetails": [
      { "0": "••." },
      { "1": "••.", },
    ],
    "Objective": [
      { 0: "" },
      { 1: "•" },
      { 2: "" },
      { 3: "" },
    ],
    "Benefits": [
      { 0: "" },
      { 1: "•" },
      { 2: "" },
      { 3: "" },
      { 4: "" },
    ],
    "Participants": [
      { 0: "" },
      { 1: "" },
      { 2: "" },
      { 3: "•" },
      { 4: "" },
      { 5: "" },
      { 6: "" },
      { 7: "" },
      { 8: "" },
      { 9: "•" },
      { 10: "" },
      { 11: "" },
      { 12: "" },
    ],
    "Photographs": [
      { url: 'assets/images/resources/outreach/activities/1/1.png' },
      { url: 'assets/images/resources/outreach/activities/1/2.png' },
      { url: 'assets/images/resources/outreach/activities/1/3.png' },
      { url: 'assets/images/resources/outreach/activities/1/4.png' },
      { url: 'assets/images/resources/outreach/activities/1/5.png' },
      { url: 'assets/images/resources/outreach/activities/1/6.png' },
    ],
  }
]